# sushi-config.yaml is documented https://fshschool.org/docs/sushi/configuration/
# ───────────────────────────────────────────────────
# the id should be lowercase made up of "ihe." + {domain acronym} + "." + {profile acronym/short-name}
# e.g. ihe.iti.mhds, or ihe.iti.basicaudit
id: ihe-europe.xshare.ybd
canonical: https://profiles.ihe-europe.net/xShare/YBD
version: 0.0.1-current
name: IHE_XSHARE_YBD
title: "xShare Yellow Button Download"
description: xShare Yellow Button Download implementable and conformance-testable specification.
releaseLabel: ci-build
#releaseLabel: ballot
#releaseLabel: trial-use
#releaseLabel: release
#date: 2022-01-02
status: draft
publisher:
  ## Find your domain contact on the https://www.ihe.net/ihe_domains page
  - name: IHE Europe Technical Committee
  - url: https://www.ihe-eruope.net/
  - email: info@ihe-europe.net
contact:
  - name: IHE Europe Technical Committee
    telecom:
      - system: email
        value: info@ihe-europe.net
license:  CC-BY-4.0
fhirVersion: 4.0.1
jurisdiction: 'http://unstats.un.org/unsd/methods/m49/m49.htm#001'
#copyright: IHE http://www.ihe.net/Governance/#Intellectual_Property
copyrightYear: 2025+
dependencies: 
  hl7.fhir.uv.cpg: 2.0.0
  hl7.fhir.uv.ips: 1.1.0
  hl7.fhir.uv.cql: 1.0.0


parameters:  # see https://confluence.hl7.org/display/FHIR/Implementation+Guide+Parameters
  path-resource:
    - input/resources
    - fsh-generated/resources
    - input/examples
#  path-pages:
#    - input/pagecontent
#    - fsh-generated/includes
  show-inherited-invariants: 'false'
  usage-stats-opt-out: 'false'
  logging: progress
  shownav: 'true'
  active-tables: 'false'
  apply-contact: 'true'
  apply-jurisdiction: 'true'
  apply-publisher: 'true'
  apply-version: 'true'

#resources:
# list every example here with a name, description and that exampleBoolean is true; These are used to populate the artifacts page, and are needed to eliminate build warnings 
# You may delay filling out this section until you approach publication as it is merely a nice to have and eliminates build warnings -- If you do this then you will need above the autoload-resources true


pages:
# itemize here each narrative page. Include assigned section numbers when appropriate. The order they appear here is the order they will appear in the TOC and on the next/prev navigation.
  index.md:
    title: Home
    generation: markdown
  YBD_v1_over.md:
    title: "Volume-1: Business Description"
    generation: markdown
  YBD_v1_actor.md:
    title: "Volume-1: Actors"
    generation: markdown
  YBD_v2.md:
    title: "Volume-2: YBD Transactions"
    generation: markdown
  YBD_v3.md:
    title: "Volume-3: YBD Content Specifications"
    generation: markdown
  YBD_v4.md:
    title: "Volume-4: Jurisdictional Contextualizations"
    generation: markdown
  testplan.md:
    title: "Test Plan"
    generation: markdown
  other.md:
    title: Changes to Other IHE Specifications
    generation: markdown
  download.md:
    title: "Download and Analysis"
    generation: markdown
  issues.md:
    title: Significant Changes and Issues
    generation: markdown

menu:
  Home: index.html
  Vol-1 - Business Description: YBD_v1_over.html
  Vol-1 - Actors: YBD_v1_actor.html
  Vol-2 - Transactions: YBD_v2.html
  Vol-3 - Content: YBD_v3.html
  Vol-4 - Contextualizations: YBD_v4.html
  Artifacts: artifacts.html
  Other:
    Changes to Other IHE Specifications: other.html
    Download and Analysis: download.html
    Test Plan: testplan.html
